# ブルーアーカイブ 生徒マスターリスト
# 出典: https://schaledb.com/data/jp/students.min.json (2026/4/27時点)
# ゲーム内表記: オリジナルキャラはファーストネームのみ、コラボキャラはフルネーム
# ホシノ（臨戦）はタンク・ディーラーの2形態が同名のため1件に統合（計259件）

STUDENTS_MASTER = [
    'アル',
    'エイミ',
    'ハルナ',
    'ヒフミ',
    'ヒナ',
    'ホシノ',
    'イオリ',
    'マキ',
    'ネル',
    'イズミ',
    'シロコ',
    'シュン',
    'スミレ',
    'ツルギ',
    'アカネ',
    'チセ',
    'アカリ',
    'ハスミ',
    'ノノミ',
    'カヨコ',
    'ムツキ',
    'ジュンコ',
    'セリカ',
    'ツバキ',
    'ユウカ',
    'ハルカ',
    'アスナ',
    'コトリ',
    'スズミ',
    'フィーナ',
    'ヒビキ',
    'カリン',
    'サヤ',
    'アイリ',
    'フウカ',
    'ハナエ',
    'ハレ',
    'ウタハ',
    'アヤネ',
    'チナツ',
    'コタマ',
    'ジュリ',
    'セリナ',
    'シミコ',
    'ヨシミ',
    'マシロ',
    'イズナ',
    'シズコ',
    'アリス',
    'ミドリ',
    'モモイ',
    'チェリノ',
    'ノドカ',
    'ユズ',
    'アズサ',
    'ハナコ',
    'コハル',
    'アズサ（水着）',
    'マシロ（水着）',
    'ツルギ（水着）',
    'ヒフミ（水着）',
    'ヒナ（水着）',
    'イオリ（水着）',
    'イズミ（水着）',
    'シロコ（ライディング）',
    'シュン（幼女）',
    'キリノ',
    'サヤ（私服）',
    'ネル（バニーガール）',
    'カリン（バニーガール）',
    'アスナ（バニーガール）',
    'ナツ',
    'マリー',
    '初音ミク',
    'アコ',
    'チェリノ（温泉）',
    'チナツ（温泉）',
    'トモエ',
    'ノドカ（温泉）',
    'アル（正月）',
    'ムツキ（正月）',
    'セリカ（正月）',
    'ワカモ',
    'フブキ',
    'セナ',
    'チヒロ',
    'ミモリ',
    'ウイ',
    'ヒナタ',
    'マリナ',
    'ミヤコ',
    'サキ',
    'ミユ',
    'カエデ',
    'イロハ',
    'ミチル',
    'ツクヨ',
    'ミサキ',
    'ヒヨリ',
    'アツコ',
    'ワカモ（水着）',
    'ノノミ（水着）',
    'アヤネ（水着）',
    'ホシノ（水着）',
    'シズコ（水着）',
    'イズナ（水着）',
    'チセ（水着）',
    'サオリ',
    'モエ',
    'カズサ',
    'ココナ',
    'ウタハ（応援団）',
    'ノア',
    'ヒビキ（応援団）',
    'アカネ（バニーガール）',
    'ユウカ（体操服）',
    'マリー（体操服）',
    'ハスミ（体操服）',
    'ヒマリ',
    'シグレ',
    'セリナ（クリスマス）',
    'ハナエ（クリスマス）',
    'ハルナ（正月）',
    'フウカ（正月）',
    'ジュンコ（正月）',
    'ミネ',
    'ミカ',
    'メグ',
    'カンナ',
    'サクラコ',
    'トキ',
    'ナギサ',
    'コユキ',
    'カヨコ（正月）',
    'ハルカ（正月）',
    'カホ',
    'アリス（メイド）',
    'トキ（バニーガール）',
    'ユズ（メイド）',
    'レイサ',
    'ルミ',
    'ミナ',
    'ミノリ',
    'ミヤコ（水着）',
    'サキ（水着）',
    'ミユ（水着）',
    'シロコ（水着）',
    'ウイ（水着）',
    'ヒナタ（水着）',
    'コハル（水着）',
    'ハナコ（水着）',
    'ミモリ（水着）',
    'メル',
    'モミジ',
    'コトリ（応援団）',
    'ハルナ（体操服）',
    'イチカ',
    'カスミ',
    'シグレ（温泉）',
    '御坂美琴',
    '食蜂操祈',
    '佐天涙子',
    'ユカリ',
    'レンゲ',
    'キキョウ',
    'エイミ（水着）',
    'コタマ（キャンプ）',
    'ハレ（キャンプ）',
    'アコ（ドレス）',
    'イブキ',
    'マコト',
    'ヒナ（ドレス）',
    'カヨコ（ドレス）',
    'アル（ドレス）',
    'アカリ（正月）',
    'ウミカ',
    'ツバキ（ガイド）',
    'カズサ（バンド）',
    'ヨシミ（バンド）',
    'アイリ（バンド）',
    'キララ',
    'モモイ（メイド）',
    'ミドリ（メイド）',
    'セリカ（水着）',
    'カンナ（水着）',
    'フブキ（水着）',
    'キリノ（水着）',
    'モエ（水着）',
    'ホシノ（臨戦）',
    'シロコ＊テラー',
    'アツコ（水着）',
    'サオリ（水着）',
    'ヒヨリ（水着）',
    'マリナ（チーパオ）',
    'トモエ（チーパオ）',
    'レイジョ',
    'キサキ',
    'マリー（アイドル）',
    'サクラコ（アイドル）',
    'ミネ（アイドル）',
    'チアキ',
    'サツキ',
    'ユウカ（パジャマ）',
    'ノア（パジャマ）',
    'セイア',
    'アスナ（制服）',
    'カリン（制服）',
    'ネル（制服）',
    'リオ',
    'マキ（キャンプ）',
    'セナ（私服）',
    'ジュリ（アルバイト）',
    'イズミ（正月）',
    'レイ',
    'スミレ（アルバイト）',
    'サオリ（ドレス）',
    'ヒカリ',
    'ノゾミ',
    'アオバ',
    'フィーナ（ガイド）',
    'ナグサ',
    'ニヤ',
    'ナツ（バンド）',
    'ユカリ（水着）',
    'レンゲ（水着）',
    'キキョウ（水着）',
    'セイア（水着）',
    'ハスミ（水着）',
    'イチカ（水着）',
    'ナギサ（水着）',
    'ミカ（水着）',
    'エリ',
    'カノエ',
    'ミサキ（水着）',
    'ミヨ',
    'フユ',
    'リツ',
    'レイサ（マジカル）',
    'スズミ（マジカル）',
    'ラブ',
    'スバル',
    'タカネ',
    'ヤクモ',
    'ツクヨ（ドレス）',
    'ミチル（ドレス）',
    'リオ（臨戦）',
    'トキ（臨戦）',
    'ヒマリ（臨戦）',
    'アリス（臨戦）',
    'ケイ',
    'エイミ（臨戦）',
    'ユズ（臨戦）',
    'コユキ（パジャマ）',
    'コノカ',
    'レナ',
    'アカネ（制服）',
    'ニコ',
    'クルミ',
    'オトギ',
]

# 出典: https://bluearchive.wikiru.jp/?キャラクター一覧 (2026/4/29時点)
# role: STRIKER / SPECIAL
# position: FRONT / MIDDLE / BACK
# cls: タンク / アタッカー / サポーター / ヒーラー / T.S
# school: 学校名
# atk_type: 爆発 / 神秘 / 貫通 / 振動
# def_type: 軽装備 / 重装甲 / 特殊装甲 / 弾力装甲 / 複合装甲
STUDENTS_INFO: dict[str, dict] = {
    "アイリ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "トリニティ", "atk_type": "爆発", "def_type": "軽装備"},
    "アイリ（バンド）": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "トリニティ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "アオバ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ハイランダー", "atk_type": "振動", "def_type": "軽装備"},
    "アカネ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "アカネ（バニーガール）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "重装甲"},
    "アカネ（制服）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "アカリ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "重装甲"},
    "アカリ（正月）": {"role": "SPECIAL", "position": "BACK", "cls": "T.S", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "アコ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "重装甲"},
    "アコ（ドレス）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "アスナ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "軽装備"},
    "アスナ（バニーガール）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ミレニアム", "atk_type": "神秘", "def_type": "軽装備"},
    "アスナ（制服）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ミレニアム", "atk_type": "爆発", "def_type": "重装甲"},
    "アツコ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "アリウス", "atk_type": "爆発", "def_type": "特殊装甲"},
    "アツコ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "アリウス", "atk_type": "振動", "def_type": "特殊装甲"},
    "アヤネ": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "アビドス", "atk_type": "貫通", "def_type": "軽装備"},
    "アヤネ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "T.S", "school": "アビドス", "atk_type": "貫通", "def_type": "軽装備"},
    "アリス": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "特殊装甲"},
    "アリス（メイド）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "軽装備"},
    "アリス（臨戦）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "複合装甲"},
    "アル": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "アル（正月）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "特殊装甲"},
    "アル（ドレス）": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "重装甲"},
    "イオリ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "重装甲"},
    "イオリ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "イズナ": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "軽装備"},
    "イズナ（水着）": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "特殊装甲"},
    "イズミ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "イズミ（正月）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "イズミ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "イチカ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "トリニティ", "atk_type": "振動", "def_type": "重装甲"},
    "イチカ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "トリニティ", "atk_type": "振動", "def_type": "特殊装甲"},
    "イブキ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "重装甲"},
    "イロハ": {"role": "SPECIAL", "position": "BACK", "cls": "T.S", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "重装甲"},
    "ウイ": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "トリニティ", "atk_type": "爆発", "def_type": "軽装備"},
    "ウイ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "トリニティ", "atk_type": "貫通", "def_type": "弾力装甲"},
    "ウタハ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "重装甲"},
    "ウタハ（応援団）": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ウミカ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "特殊装甲"},
    "エイミ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "エイミ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "神秘", "def_type": "特殊装甲"},
    "エイミ（臨戦）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "エリ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ワイルドハント", "atk_type": "振動", "def_type": "特殊装甲"},
    "オトギ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "SRT", "atk_type": "爆発", "def_type": "特殊装甲"},
    "カエデ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "爆発", "def_type": "特殊装甲"},
    "カズサ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "貫通", "def_type": "重装甲"},
    "カズサ（バンド）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "カスミ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "振動", "def_type": "重装甲"},
    "カノエ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ワイルドハント", "atk_type": "神秘", "def_type": "重装甲"},
    "カホ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "重装甲"},
    "カヨコ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "重装甲"},
    "カヨコ（正月）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "カヨコ（ドレス）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "軽装備"},
    "カリン": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "重装甲"},
    "カリン（バニーガール）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "重装甲"},
    "カリン（制服）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "重装甲"},
    "カンナ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ヴァルキューレ", "atk_type": "貫通", "def_type": "重装甲"},
    "カンナ（水着）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ヴァルキューレ", "atk_type": "爆発", "def_type": "軽装備"},
    "キキョウ": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "振動", "def_type": "重装甲"},
    "キキョウ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "振動", "def_type": "重装甲"},
    "キサキ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "山海経", "atk_type": "振動", "def_type": "弾力装甲"},
    "キキョウ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "振動", "def_type": "重装甲"},
    "キララ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "振動", "def_type": "軽装備"},
    "キリノ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ヴァルキューレ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "キリノ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ヴァルキューレ", "atk_type": "神秘", "def_type": "重装甲"},
    "クルミ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "SRT", "atk_type": "爆発", "def_type": "軽装備"},
    "ケイ": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "神秘", "def_type": "複合装甲"},
    "ココナ": {"role": "STRIKER", "position": "MIDDLE", "cls": "ヒーラー", "school": "山海経", "atk_type": "貫通", "def_type": "特殊装甲"},
    "コタマ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "コタマ（キャンプ）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ミレニアム", "atk_type": "貫通", "def_type": "重装甲"},
    "コトリ": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "コトリ（応援団）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "特殊装甲"},
    "コノカ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ヴァルキューレ", "atk_type": "神秘", "def_type": "軽装備"},
    "コハル": {"role": "STRIKER", "position": "BACK", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "コハル（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "神秘", "def_type": "重装甲"},
    "コユキ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "神秘", "def_type": "重装甲"},
    "コユキ（パジャマ）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "神秘", "def_type": "軽装備"},
    "サオリ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アリウス", "atk_type": "爆発", "def_type": "特殊装甲"},
    "サオリ（水着）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アリウス", "atk_type": "神秘", "def_type": "重装甲"},
    "サオリ（ドレス）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アリウス", "atk_type": "振動", "def_type": "軽装備"},
    "サキ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "SRT", "atk_type": "貫通", "def_type": "特殊装甲"},
    "サキ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "SRT", "atk_type": "爆発", "def_type": "重装甲"},
    "サクラコ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "トリニティ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "サクラコ（アイドル）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "サツキ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "重装甲"},
    "サヤ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "山海経", "atk_type": "爆発", "def_type": "軽装備"},
    "サヤ（私服）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "山海経", "atk_type": "貫通", "def_type": "特殊装甲"},
    "シグレ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "レッドウィンター", "atk_type": "爆発", "def_type": "重装甲"},
    "シグレ（温泉）": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "レッドウィンター", "atk_type": "貫通", "def_type": "特殊装甲"},
    "シズコ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "特殊装甲"},
    "シズコ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "重装甲"},
    "シミコ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "トリニティ", "atk_type": "爆発", "def_type": "軽装備"},
    "シュン": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "山海経", "atk_type": "爆発", "def_type": "軽装備"},
    "シュン（幼女）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "山海経", "atk_type": "爆発", "def_type": "軽装備"},
    "シロコ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アビドス", "atk_type": "爆発", "def_type": "軽装備"},
    "シロコ（ライディング）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アビドス", "atk_type": "神秘", "def_type": "重装甲"},
    "シロコ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "アビドス", "atk_type": "神秘", "def_type": "軽装備"},
    "シロコ＊テラー": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アビドス", "atk_type": "神秘", "def_type": "特殊装甲"},
    "スズミ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "スズミ（マジカル）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "トリニティ", "atk_type": "振動", "def_type": "特殊装甲"},
    "スバル": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アリウス", "atk_type": "神秘", "def_type": "特殊装甲"},
    "スミレ": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "特殊装甲"},
    "スミレ（アルバイト）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "セイア": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "トリニティ", "atk_type": "貫通", "def_type": "弾力装甲"},
    "セイア（水着）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "トリニティ", "atk_type": "貫通", "def_type": "特殊装甲"},
    "セナ": {"role": "SPECIAL", "position": "BACK", "cls": "T.S", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "軽装備"},
    "セナ（私服）": {"role": "STRIKER", "position": "MIDDLE", "cls": "ヒーラー", "school": "ゲヘナ", "atk_type": "振動", "def_type": "重装甲"},
    "セリカ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "アビドス", "atk_type": "爆発", "def_type": "軽装備"},
    "セリカ（正月）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "アビドス", "atk_type": "貫通", "def_type": "特殊装甲"},
    "セリカ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "アビドス", "atk_type": "神秘", "def_type": "重装甲"},
    "セリナ": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "神秘", "def_type": "軽装備"},
    "セリナ（クリスマス）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "トリニティ", "atk_type": "貫通", "def_type": "特殊装甲"},
    "タカネ": {"role": "STRIKER", "position": "MIDDLE", "cls": "ヒーラー", "school": "レッドウィンター", "atk_type": "神秘", "def_type": "軽装備"},
    "チアキ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "振動", "def_type": "特殊装甲"},
    "チェリノ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "レッドウィンター", "atk_type": "貫通", "def_type": "軽装備"},
    "チェリノ（温泉）": {"role": "SPECIAL", "position": "BACK", "cls": "T.S", "school": "レッドウィンター", "atk_type": "爆発", "def_type": "重装甲"},
    "チセ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "重装甲"},
    "チセ（水着）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "軽装備"},
    "チナツ": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "軽装備"},
    "チナツ（温泉）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "軽装備"},
    "チヒロ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "重装甲"},
    "ツクヨ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "軽装備"},
    "ツクヨ（ドレス）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "百鬼夜行", "atk_type": "貫通", "def_type": "軽装備"},
    "ツバキ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "百鬼夜行", "atk_type": "貫通", "def_type": "特殊装甲"},
    "ツバキ（ガイド）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "貫通", "def_type": "重装甲"},
    "ツルギ": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "トリニティ", "atk_type": "貫通", "def_type": "重装甲"},
    "ツルギ（水着）": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "トリニティ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "トキ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "弾力装甲"},
    "トキ（バニーガール）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "トキ（臨戦）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "トモエ": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "レッドウィンター", "atk_type": "貫通", "def_type": "特殊装甲"},
    "トモエ（チーパオ）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "レッドウィンター", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ナギサ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "ナギサ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "トリニティ", "atk_type": "振動", "def_type": "弾力装甲"},
    "ナグサ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "振動", "def_type": "弾力装甲"},
    "ナツ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "トリニティ", "atk_type": "神秘", "def_type": "重装甲"},
    "ナツ（バンド）": {"role": "STRIKER", "position": "FRONT", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ニコ": {"role": "STRIKER", "position": "FRONT", "cls": "サポーター", "school": "SRT", "atk_type": "爆発", "def_type": "弾力装甲"},
    "ニヤ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "振動", "def_type": "重装甲"},
    "ネル": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "ネル（バニーガール）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ミレニアム", "atk_type": "爆発", "def_type": "重装甲"},
    "ネル（制服）": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "弾力装甲"},
    "ノア": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ミレニアム", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ノア（パジャマ）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "ノゾミ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ハイランダー", "atk_type": "振動", "def_type": "軽装備"},
    "ノドカ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "レッドウィンター", "atk_type": "爆発", "def_type": "重装甲"},
    "ノドカ（温泉）": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "レッドウィンター", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ノノミ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "アビドス", "atk_type": "貫通", "def_type": "軽装備"},
    "ノノミ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "アビドス", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ハスミ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "貫通", "def_type": "重装甲"},
    "ハスミ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "貫通", "def_type": "軽装備"},
    "ハスミ（体操服）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ハナエ": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "ハナエ（クリスマス）": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ハナコ": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "貫通", "def_type": "特殊装甲"},
    "ハナコ（水着）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "トリニティ", "atk_type": "振動", "def_type": "重装甲"},
    "ハルカ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "ハルカ（正月）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "ハルナ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "重装甲"},
    "ハルナ（正月）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "ハルナ（体操服）": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "ゲヘナ", "atk_type": "振動", "def_type": "重装甲"},
    "ハレ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "ハレ（キャンプ）": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "ヒカリ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ハイランダー", "atk_type": "振動", "def_type": "軽装備"},
    "ヒナ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "重装甲"},
    "ヒナ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "重装甲"},
    "ヒナ（ドレス）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "弾力装甲"},
    "ヒナタ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "トリニティ", "atk_type": "神秘", "def_type": "重装甲"},
    "ヒナタ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "爆発", "def_type": "軽装備"},
    "ヒビキ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "重装甲"},
    "ヒビキ（応援団）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "軽装備"},
    "ヒフミ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "トリニティ", "atk_type": "貫通", "def_type": "軽装備"},
    "ヒフミ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "T.S", "school": "トリニティ", "atk_type": "貫通", "def_type": "重装甲"},
    "ヒマリ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "ヒマリ（臨戦）": {"role": "SPECIAL", "position": "BACK", "cls": "T.S", "school": "ミレニアム", "atk_type": "貫通", "def_type": "弾力装甲"},
    "ヒヨリ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "アリウス", "atk_type": "爆発", "def_type": "軽装備"},
    "ヒヨリ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "アリウス", "atk_type": "貫通", "def_type": "重装甲"},
    "フィーナ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "貫通", "def_type": "軽装備"},
    "フィーナ（ガイド）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "爆発", "def_type": "重装甲"},
    "フウカ": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "重装甲"},
    "フウカ（正月）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "特殊装甲"},
    "フブキ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ヴァルキューレ", "atk_type": "貫通", "def_type": "重装甲"},
    "フブキ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ヴァルキューレ", "atk_type": "爆発", "def_type": "重装甲"},
    "フユ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ワイルドハント", "atk_type": "振動", "def_type": "特殊装甲"},
    "ホシノ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "アビドス", "atk_type": "貫通", "def_type": "重装甲"},
    "ホシノ（水着）": {"role": "STRIKER", "position": "FRONT", "cls": "サポーター", "school": "アビドス", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ホシノ（臨戦）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "アビドス", "atk_type": "神秘", "def_type": "重装甲"},
    "マキ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "マキ（キャンプ）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "重装甲"},
    "マコト": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "特殊装甲"},
    "マシロ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "マシロ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "神秘", "def_type": "軽装備"},
    "マリー": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "トリニティ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "マリー（体操服）": {"role": "STRIKER", "position": "MIDDLE", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "神秘", "def_type": "特殊装甲"},
    "マリー（アイドル）": {"role": "STRIKER", "position": "MIDDLE", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "マリナ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "レッドウィンター", "atk_type": "貫通", "def_type": "軽装備"},
    "マリナ（チーパオ）": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "レッドウィンター", "atk_type": "貫通", "def_type": "重装甲"},
    "ミカ": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "トリニティ", "atk_type": "貫通", "def_type": "軽装備"},
    "ミカ（水着）": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "トリニティ", "atk_type": "振動", "def_type": "特殊装甲"},
    "ミサキ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "アリウス", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ミサキ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "アリウス", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ミチル": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "軽装備"},
    "ミチル（ドレス）": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "百鬼夜行", "atk_type": "爆発", "def_type": "軽装備"},
    "ミドリ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "ミドリ（メイド）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "振動", "def_type": "軽装備"},
    "ミナ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "山海経", "atk_type": "爆発", "def_type": "重装甲"},
    "ミネ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "トリニティ", "atk_type": "爆発", "def_type": "軽装備"},
    "ミネ（アイドル）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "ミノリ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "レッドウィンター", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ミモリ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "軽装備"},
    "ミモリ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ミヤコ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "SRT", "atk_type": "貫通", "def_type": "重装甲"},
    "ミヤコ（水着）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "SRT", "atk_type": "爆発", "def_type": "重装甲"},
    "ミユ": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "SRT", "atk_type": "貫通", "def_type": "軽装備"},
    "ミユ（水着）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "SRT", "atk_type": "爆発", "def_type": "軽装備"},
    "ミヨ": {"role": "STRIKER", "position": "BACK", "cls": "サポーター", "school": "ワイルドハント", "atk_type": "振動", "def_type": "弾力装甲"},
    "ムツキ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "ムツキ（正月）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "重装甲"},
    "メグ": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "メル": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "レッドウィンター", "atk_type": "貫通", "def_type": "軽装備"},
    "モエ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "SRT", "atk_type": "貫通", "def_type": "軽装備"},
    "モエ（水着）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "SRT", "atk_type": "振動", "def_type": "特殊装甲"},
    "モミジ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "レッドウィンター", "atk_type": "振動", "def_type": "重装甲"},
    "モモイ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "軽装備"},
    "モモイ（メイド）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "振動", "def_type": "軽装備"},
    "ヤクモ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "レッドウィンター", "atk_type": "爆発", "def_type": "軽装備"},
    "ユウカ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ミレニアム", "atk_type": "爆発", "def_type": "重装甲"},
    "ユウカ（体操服）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ミレニアム", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ユウカ（パジャマ）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ミレニアム", "atk_type": "爆発", "def_type": "重装甲"},
    "ユカリ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "振動", "def_type": "重装甲"},
    "ユカリ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "貫通", "def_type": "軽装備"},
    "ユズ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "貫通", "def_type": "特殊装甲"},
    "ユズ（メイド）": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "弾力装甲"},
    "ユズ（臨戦）": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ヨシミ": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "トリニティ", "atk_type": "貫通", "def_type": "重装甲"},
    "ヨシミ（バンド）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "トリニティ", "atk_type": "爆発", "def_type": "特殊装甲"},
    "ラブ": {"role": "STRIKER", "position": "FRONT", "cls": "アタッカー", "school": "トリニティ", "atk_type": "振動", "def_type": "特殊装甲"},
    "レイ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "振動", "def_type": "軽装備"},
    "レイサ": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "トリニティ", "atk_type": "貫通", "def_type": "重装甲"},
    "レイサ（マジカル）": {"role": "SPECIAL", "position": "BACK", "cls": "ヒーラー", "school": "トリニティ", "atk_type": "振動", "def_type": "特殊装甲"},
    "レイジョ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "山海経", "atk_type": "神秘", "def_type": "重装甲"},
    "レナ": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "ワイルドハント", "atk_type": "爆発", "def_type": "軽装備"},
    "レンゲ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "振動", "def_type": "重装甲"},
    "レンゲ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "振動", "def_type": "特殊装甲"},
    "リオ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ミレニアム", "atk_type": "神秘", "def_type": "弾力装甲"},
    "リオ（臨戦）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ミレニアム", "atk_type": "爆発", "def_type": "特殊装甲"},
    "リツ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ワイルドハント", "atk_type": "神秘", "def_type": "特殊装甲"},
    "ルミ": {"role": "STRIKER", "position": "FRONT", "cls": "ヒーラー", "school": "山海経", "atk_type": "爆発", "def_type": "重装甲"},
    "ワカモ": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "神秘", "def_type": "軽装備"},
    "ワカモ（水着）": {"role": "STRIKER", "position": "BACK", "cls": "アタッカー", "school": "百鬼夜行", "atk_type": "貫通", "def_type": "重装甲"},
    "初音ミク": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "その他", "atk_type": "爆発", "def_type": "軽装備"},
    "御坂美琴": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "常盤台中学", "atk_type": "貫通", "def_type": "重装甲"},
    "食蜂操祈": {"role": "STRIKER", "position": "MIDDLE", "cls": "サポーター", "school": "常盤台中学", "atk_type": "爆発", "def_type": "重装甲"},
    "佐天涙子": {"role": "SPECIAL", "position": "BACK", "cls": "アタッカー", "school": "柵川中学", "atk_type": "貫通", "def_type": "特殊装甲"},
    "アズサ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "トリニティ", "atk_type": "爆発", "def_type": "重装甲"},
    "アズサ（水着）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "トリニティ", "atk_type": "神秘", "def_type": "軽装備"},
    "ジュリ": {"role": "SPECIAL", "position": "BACK", "cls": "サポーター", "school": "ゲヘナ", "atk_type": "爆発", "def_type": "軽装備"},
    "ジュリ（アルバイト）": {"role": "STRIKER", "position": "FRONT", "cls": "タンク", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "軽装備"},
    "ジュンコ": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "貫通", "def_type": "軽装備"},
    "ジュンコ（正月）": {"role": "STRIKER", "position": "MIDDLE", "cls": "アタッカー", "school": "ゲヘナ", "atk_type": "神秘", "def_type": "重装甲"},
}
